---
minimum_pre_commit_version: 1.15.2
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-merge-conflict  # Check for files that contain merge conflict strings.
      - id: trailing-whitespace   # Trims trailing whitespace.
        args: [--markdown-linebreak-ext=md]
      - id: mixed-line-ending     # Replaces or checks mixed line ending.
        args: [--fix=lf]
      - id: end-of-file-fixer     # Makes sure files end in a newline and only a newline.
      - id: check-merge-conflict  # Check for files that contain merge conflict strings.
      - id: check-ast             # Simply check whether files parse as valid python.

  # ----- Code Formatting and Analysis ---------------------------------------------------------->
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.7.2"
    hooks:
      - id: ruff
        args:
          - --fix
        exclude: (.pre-commit-hooks/.*|docs/.*)\.py

  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        args: [-l 100]
        exclude: ^tests/([^/]*/)*files/.*

  - repo: https://github.com/asottile/blacken-docs
    rev: 1.19.1
    hooks:
      - id: blacken-docs
        args: [--skip-errors]
        files: ^(docs/.*\.rst|src/codemod/.*\.py)$
        additional_dependencies:
          - black==24.10.0

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
      - id: mypy
        name: Run mypy against the code base
        files: ^(src/|tests/|examples/).*\.py$
        args: []
        exclude: ^tests/([^/]*/)*files/.*
        additional_dependencies:
          - libcst
          - sqlfluff
          - pydantic
          - tomllib >= 1.1.0; python_version < "3.11"
  # <---- Code Formatting and Analysis -----------------------------------------------------------
