site_name: Codemod Documentation
strict: true
theme:
  name: material
  logo: imgs/recode.png
  icon: imgs/recode.png
  favicon: imgs/recode.png
  palette:
    primary: blue grey
    accent: organge
    scheme: slate

  features:
    - announce.dismiss
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.preview
    - navigation.instant.progress
    - navigation.path
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.suggest
    - toc.follow

docs_dir: docs
site_dir: site

# https://www.mkdocs.org/user-guide/configuration/#validation
validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn

plugins:
  - autorefs
  - search
  - exclude:
      glob:
      - plugins/*
      - __pycache__/*
  - mkdocstrings:
      default_handler: python
      enable_inventory: true
      handlers:
        python_xref:
          import:
            - "https://docs.pydantic.dev/latest/objects.inv"
            - "https://docs.python.org/3/objects.inv"
          options:
            docstring_style: "sphinx"
            docstring_section_style: "list"
            relative_crossrefs: true
            show_root_heading: true
            show_signature: true
            unwrap_annotated: true
        python:
          paths: [../src]
          options:
            members_order: source
            separate_signature: true
            filters: ["!^_"]
            docstring_options:
              ignore_init_summary: true
            merge_init_into_class: true
            show_signature_annotations: true
            signature_crossrefs: true
            extensions:
            - griffe_pydantic:
                schema: true

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight
  - toc:
      permalink: true
      separator: "-"

watch:
  - src
  - docs

nav:
  - Home: index.md
  - Installation: installation.md
#  - Usage: usage.md
  - Configuration: config.md
#  - Examples: examples.md
#  - Contributing: contributing.md
#  - License: license.md
